### ISSUE TITLE
program crash

### ISSUE THREAD

**Issue by David9591** [luigivieira/emotions#4]
Dear Author:
    Thank you for your work, but when I actually run it, I ran into a problem.When I execute
 `python test.py -i 0` , 
the light of the camera will light up, and then the program will report an error:
`File "*****\emotions-master\emotions.py", line 91, in __init__ raise InvalidModelException('Could not load model from file: {}'.format(self._modelFile))emotions.
InvalidModelException: Could not load model from file: ****\emotions-master\models\emotions_model.dat`
I have no solution,My environment is configured as follows :

----------------------------------------------------------------
certifi                 2021.5.30        
cycler                 0.10.0                  
decorator           4.4.2                     
dlib                    19.22.0                
imageio              2.9.0                   
joblib                  1.0.1                    
kiwisolver           1.3.1                    
matplotlib           3.3.4                   
networkx             2.5.1                    
numpy                1.19.5                  
opencv-python   3.4.0.14                  
Pillow                    8.3.0                    
pip                       21.1.3          
pyparsing             2.4.7                   
python                 3.6.13               
python-dateutil    2.8.1                    
PyWavelets           1.1.1                    
scikit-image          0.17.2               
scikit-learn             0.24.2                   
scipy                      1.5.4                     
setuptools              52.0.0           
six                          1.16.0                   
sqlite                     3.36.0             
threadpoolctl          2.1.0                 
tifffile                     2020.9.3                 
vc                           14.2                
vs2015_runtime     14.27.29016         
wheel                     0.36.2             
wincertstore             0.2
-----------------------------------------------------------------

**Comment by luigivieira** [comment]
Hi David. Thank you for point this out. From the error message, the error is being thrown while the scikit-learn module is trying to load the trained model from the file. I honestly don't know the cause, but I would say it can be one of the following:

- The file is corrupted.  This is in my opinion the least possible cause, but you can try to download the file again just in case.
- There was a breaking change in a newer version of the scikit-learn package regarding the way SVM models are stored/loaded. In my view this is more likely the cause, and you can try to confirm that by simply using the older version that I indicate in my README. If it works, it is definitely related to the version of that package. Perhaps the documentation also has some information on breaking changes? If you have the chance, just take at new look at it.

Sorry if this is not much helpful, but I have not played with this code in a long time and unfortunately I don't have much free time to explore the issue by myself.

**Comment by David9591** [comment]
> Hi David. Thank you for point this out. From the error message, the error is being thrown while the scikit-learn module is trying to load the trained model from the file. I honestly don't know the cause, but I would say it can be one of the following:
> 
> * The file is corrupted.  This is in my opinion the least possible cause, but you can try to download the file again just in case.
> * There was a breaking change in a newer version of the scikit-learn package regarding the way SVM models are stored/loaded. In my view this is more likely the cause, and you can try to confirm that by simply using the older version that I indicate in my README. If it works, it is definitely related to the version of that package. Perhaps the documentation also has some information on breaking changes? If you have the chance, just take at new look at it.
> 
> Sorry if this is not much helpful, but I have not played with this code in a long time and unfortunately I don't have much free time to explore the issue by myself.

Thank you for your prompt reply！I created a new virtual environment, and in strict accordance with the minimum configuration version, the program runs a success！Since my computer has a general configuration and there are some lags in operation, I will study this project carefully next, thank you again for your excellent work!

**Comment by luigivieira** [comment]
No problem. Thank you for your kind words. Best of luck to you. :) Cheers.
